name: Build

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: install deps
      run: sudo apt install check libcurl4 libcurl4-openssl-dev libgd-dev libgd-tools
    - name: autoconf
      run: autoreconf -i
    - name: configure
      run: ./configure --enable-gcc-pch --disable-collect --enable-mapper
    - name: build
      run: make -j $(nproc)
    - name: run cmake
      run: cmake -G Ninja . -DTEST=ON
    - name: cmake build
      run: cmake --build .
    - name: fetch arch
      run: git clone --depth=1 https://git.code.sf.net/p/crossfire/crossfire-arch lib/arch
    - name: fetch maps
      run: git clone --depth=1 https://git.code.sf.net/p/crossfire/crossfire-maps lib/maps
    - name: test
      run: cd test && ctest -j --output-on-failure

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            flex
            mingw-w64-x86_64-curl
            mingw-w64-x86_64-gcc
          pacboy: >-
            cmake:p
            ninja:p

      - name: run cmake
        shell: msys2 {0}
        run: cmake -B build -G Ninja -DCMAKE_INSTALL_PREFIX=. -DMAPPER=OFF

      - name: cmake build
        shell: msys2 {0}
        run: cmake --build build

      - name: build artifacts
        shell: msys2 {0}
        working-directory: ./build
        run: cpack -G ZIP

      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-artifacts
          archive: false
          path: build/*.zip
